/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  mySidebar: {
    "DeepGo Intro": [
      'Intro',
    ],
    "Guides": [
      "Check-Ratings",
      "Import-Assets",
      "Utilize-Strategies",
      "Fund-Terms",
      "Tranche-Funds",
      "Launch-Funds",
    ],
    "Tokenomics": [
      "Governance-Token-DGT",
      "Reputation-NFT-Voyager",
      "Utility-Token-DSP",
    ],
    "CDO Protocol": [
      "Collateralized-DEX-Offering",
      "CDO-Core-Concepts",
      "Security-And-Transparency"
    ],
  },
};
