/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  mySidebar: {
    "DeepGo Intro": [
      'intro',
    ],
    "Mechanism": [
      "Collateralized-DEX-Offering",
      "CDO-Core-Concepts",
      // "The-Economics-of-CDO"
    ],
    "Contract": [
      "Deployment-Information",
      "Audit",
      // "Bug-Bounty",
    ],
    "How to Guides": [
      "How-to-Import-Assets",
      "Terminology",
      "How-to-Manage-Project",
      "How-to-Invest",
      "How-to-Check-Ratings"
    ],
    "Tokenomics": [
      "DGTnomics-V1",
    ],
    "DeepGo NFT": [
      "Core-Features",
    ],
    "Whitepaper": [
      "Whitepaper",
      // "Roadmap",
      // "Disclaimers"
    ],
    "FAQ": [
      "FAQ"
    ],
  },
};
