/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  mySidebar: {
    "DeepGo Intro": [
      'intro',
    ],
    "Guides": [
      {
        type: 'category',
        label: 'Rating',
        items: [
          "How-to-Check-Ratings",
          "Rating-Indicators",
        ],
      },
      {
        type: 'category',
        label: 'Strategy',
        items: [
          "How-to-Import-Assets",
          "How-to-Share-Strategies",
        ],
      },
      {
        type: 'category',
        label: 'Invest',
        items: [
          "How-to-Invest",
          "How-to-Manage-Project",
        ],
      }
    ],
    "Tokenomics": [
      "Governance-Token-DGT",
      "Reputation-NFT-Voyager",
      "Utility-Token-DSP",
    ],
    "Project Protocol Intro": [
      "Collateralized-DEX-Offering",
      "CDO-Core-Concepts",
      "Security-And-Transparency"
    ],
  },
};
